### ISSUE TITLE
Feed navigation colors

### ISSUE THREAD

**Issue by PeterPea** [Heath-Mayocchi/Capstone-2017#94] opened 2017-08-07 02:35 UTC
As a user I want my feed to have identifiable buttons, as it would make the website easier to navigate.

Acceptance Criteria:
High contrast colors to allow users to easily distinguish that something is a button

**Comment by Heath-Mayocchi** [comment] 2017-08-11 05:25
Duplicate of issue #61

**Closed as completed by Heath-Mayocchi** 2017-08-11 05:25 UTC
Labels: Must Have
