### ISSUE TITLE
Feed colours

### ISSUE THREAD

**Issue by PeterPea** [Heath-Mayocchi/Capstone-2017#93] opened 2017-08-07 02:35 UTC
As a user I don’t want a lot of colors on the screen as it can be too straining for my eyes

Acceptance Criteria:
High contrast colors
minimum amount of colors need to be used about 3 - 4 or lower

**Comment by Heath-Mayocchi** [comment] 2017-08-11 05:24
Duplicate of issue #61

**Closed as completed by Heath-Mayocchi** 2017-08-11 05:24 UTC
Labels: Must Have
